import type { LectureNote } from './lecture';

export const fixtureLecture: LectureNote = {
  title: 'How neural networks learn', course: 'Machine Learning · Foundations', date: '2026-10-01', processingStatus: 'completed',
  overview: 'A guided introduction to how a neural network adjusts its parameters to reduce prediction error.',
  learningObjectives: ['Explain the role of weights and activations.', 'Trace one gradient-descent update.', 'Recognize why validation data matters.'],
  sections: [{ id: 'sec-activations', heading: 'From inputs to predictions', timeStart: '00:00:00', timeEnd: '00:18:20',
    explanation: 'A layer combines its inputs with learned weights, adds a bias, and passes the result through an activation function. Stacking these transformations lets the network express increasingly useful representations.',
    keyPoints: ['Weights encode learned relationships.', 'Activations add non-linearity.', 'The final layer maps representations to predictions.'],
    definitions: [{ term: 'Activation function', meaning: 'A function that transforms a neuron’s weighted input and enables non-linear behavior.' }], formulas: ['z = w · x + b'], workedExamples: [{ title: 'A two-input neuron', steps: ['Multiply each input by its weight.', 'Add the bias.', 'Apply the activation function.'] }], teacherEmphasis: ['Non-linearity is what makes depth useful.'], commonMistakes: ['Assuming a network learns by changing the input data.'], linkedVisuals: [], intuition: 'Think of each layer as a small feature detector.', whyItMatters: 'This forward pass produces the prediction that training will evaluate.', selfCheck: ['What would happen if every activation were linear?'], connections: ['The prediction becomes the starting point for measuring loss.']
  }, { id: 'sec-gradient', heading: 'Learning from error', timeStart: '00:18:20', timeEnd: '00:34:10',
    explanation: 'Training compares a prediction with a target, computes a loss, and uses gradients to estimate how each parameter should change to reduce that loss on the next pass.',
    keyPoints: ['Loss measures prediction error.', 'Gradients point toward increasing loss.', 'Gradient descent moves parameters in the opposite direction.'], definitions: [{ term: 'Gradient descent', meaning: 'An optimization method that repeatedly adjusts parameters opposite to the loss gradient.' }], formulas: ['w_next = w_current − η ∇L(w)'], workedExamples: [], teacherEmphasis: ['The learning rate controls step size.'], commonMistakes: ['Treating a lower training loss as proof of generalization.'], linkedVisuals: [], whyItMatters: 'The update rule is the bridge between an observed mistake and a changed model.', stepByStep: ['Run the forward pass.', 'Measure loss.', 'Backpropagate gradients.', 'Update parameters.'], selfCheck: ['Why can a very large learning rate make training unstable?'], connections: ['Validation checks whether the learned pattern transfers beyond training examples.'] }],
  visualHighlights: [], keyTerms: [{ term: 'Loss', meaning: 'A scalar score representing how far a prediction is from its target.' }], reviewQuestions: ['What does an activation function contribute?', 'Why does gradient descent use the negative gradient?'], examReview: ['Forward pass → loss → backpropagation → parameter update.'], uncertainItems: [], transcript: []
};
