import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { fixtureLecture } from './lib/fixture';
import { parseLectureNote } from './lib/lecture';
import './styles.css';

const note = parseLectureNote(fixtureLecture);
function Icon({ children }: { children: React.ReactNode }) { return <span className="nav-icon" aria-hidden="true">{children}</span>; }
function App() {
  const [source, setSource] = useState(''); const [activeTab, setActiveTab] = useState('Workspace'); const [notice, setNotice] = useState('');
  const handleBuild = () => setNotice(source.trim() ? 'Source captured — notebook generation is ready for the next server step.' : 'Add a lecture, question, or rough note to begin.');
  return <div className="app-shell">
    <aside className="sidebar"><div className="wordmark"><span className="wordmark-symbol">◔</span><div><strong>synq</strong><small>LEARNING WORKSPACE</small></div></div><div className="sidebar-section-label">NAVIGATE</div><nav className="side-nav" aria-label="Workspace navigation">{['Workspace','Notebook','Lectures','Mastery'].map((item,index)=><button key={item} className={activeTab===item?'active':''} onClick={()=>setActiveTab(item)}><Icon>{['⌁','▤','▱','◔'][index]}</Icon><span>{item}</span>{item==='Workspace'&&<i/>}</button>)}</nav><div className="sidebar-footer"><button><Icon>?</Icon>Help & feedback</button><div className="account"><span>JR</span><div><strong>Jordan R.</strong><small>Personal space</small></div><b>⌄</b></div></div></aside>
    <main className="content"><header className="topbar"><div className="breadcrumbs"><span>Workspace</span><b>›</b><strong>Systems Thinking</strong></div><button className="search-button" aria-label="Search">⌕</button></header><div className="page-wrap">
      <section className="hero"><div><p className="date-label">WEDNESDAY, SEPTEMBER 30</p><h1>Make sense of the next thing.</h1><p className="hero-copy">Bring a lecture, question, or rough note. Synq turns it into a learning path you can return to.</p></div><span className="fixture-pill"><i/> Fixture workspace</span></section>
      <div className="dashboard-grid"><div className="primary-column"><section className="source-card card"><div className="card-heading"><div><p className="eyebrow">START A SOURCE</p><h2>What are you learning today?</h2></div><span className="sparkle">✣</span></div><textarea value={source} onChange={event=>setSource(event.target.value)} placeholder="Paste lecture text here…" aria-label="Lecture text"/><div className="source-actions"><button className="attach-button">⌕ <span>Attach .txt or .md</span></button><button className="build-button" onClick={handleBuild}>✦ <span>Build notebook</span></button></div>{notice&&<p className="notice" role="status">{notice}</p>}</section>
        <section className="continue-section"><div className="section-title-row"><div><p className="eyebrow">CONTINUE LEARNING</p><h2>Your notebook</h2></div><button className="library-button">Open library <span>↗</span></button></div><article className="notebook-card card"><div className="notebook-main"><div className="ready-label"><i/> FIXTURE READY <span>Updated just now</span></div><h3>{note.title}</h3><p>{note.overview}</p><div className="notebook-meta"><span>{note.sections.length} sections</span><span>{note.reviewQuestions.length} review prompts</span></div><button className="read-button">Read notebook <span>↗</span></button></div><div className="notebook-outline"><p className="eyebrow">IN THIS NOTEBOOK</p>{note.sections.map((section,index)=><a href={'#'+section.id} key={section.id}><strong>0{index+1}</strong><span>{section.heading}<small>{section.timeStart}</small></span></a>)}</div></article></section>
        <section className="lesson card" id={note.sections[0].id}><div className="lesson-heading"><div><p className="eyebrow">SECTION 01</p><h2>{note.sections[0].heading}</h2><span className="timecode">{note.sections[0].timeStart} — {note.sections[0].timeEnd}</span></div><button className="more-button">•••</button></div><p className="lesson-copy">{note.sections[0].explanation}</p><div className="lesson-columns"><div><p className="eyebrow">KEY POINTS</p>{note.sections[0].keyPoints.map(point=><div className="key-point" key={point}><i>↗</i>{point}</div>)}</div><div><p className="eyebrow">TERMS TO KEEP</p>{note.sections[0].definitions.map(definition=><div className="term" key={definition.term}><strong>{definition.term}</strong><span>{definition.meaning}</span></div>)}</div></div></section>
      </div><aside className="right-column"><section className="side-card card"><div className="side-card-heading"><p className="eyebrow">SOURCE CONTEXT</p><button>•••</button></div><div className="file-row"><span className="file-icon">▤</span><div><strong>systems-thinking.md</strong><small>Text source · 34 min</small></div></div><div className="signal"><p className="eyebrow">CURRENT SIGNAL <span><i/> live</span></p><p>The notebook is rendered from a validated structured fixture. Every section, visual, and transcript line keeps a stable source link.</p></div><button className="review-source" onClick={()=>setNotice('Source context is ready for review.')}>Review source <span>↗</span></button></section><section className="side-card card objectives"><div className="objectives-title"><p className="eyebrow">LEARNING OBJECTIVES</p><b>{note.learningObjectives.length}</b></div>{note.learningObjectives.map((objective,index)=><div className="objective" key={objective}><strong>0{index+1}</strong><span>{objective}</span></div>)}</section><section className="next-action"><p className="eyebrow">NEXT USEFUL ACTION</p><h3>Check your recall</h3><p>Three short prompts are ready when you are.</p><button className="start-review" onClick={()=>setNotice('Review session queued for the next product slice.')}>Start review <span>→</span></button></section></aside></div>
    </div></main></div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
